language: go

go:
  - '1.13'

env:
  global:
    - GOFLAGS="-trimpath"

go_import_path: arnested.dk/go/healthy

before_install:
  - GO111MODULE=off go get github.com/mitchellh/gox
  - GO111MODULE=off go get github.com/robertkrimen/godocdown/godocdown
  - GO111MODULE=off go get github.com/frapposelli/wwhrd
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

before_script:
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make doc ; git diff --quiet # Check the docs are up to date
  - go test -v -race -coverprofile=c.out -covermode=atomic ./...
  - ln c.out coverage.txt # Cover profile should be detected by both CodeClimate and CodeCov
  - go mod vendor && wwhrd check

after_script:
  - rm -rf vendor
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"

deploy:
  # Deploy to Github Releases
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: FeQa2Hoh7YwLQLGsEyDrED8X6lhEFwcswMfHFIaVWFbZSMQjFovRmM4a+77Clelm4uHZe7HmYiTujY16vNc4tVwZSvyVpvfQnHIGQDnZvKWDoqw1xRN2yQi+rm2WfUHqE5/mVdB9qTAoJM+qPftcxKzFtH2/rDhG3j5BwnJX8US2KZGqZUdYHpHMRkWkAOVhqe7hZrfZbAuBzz7eDh04C/sjnQleRf+zelqA26tMbriQAqdUQKEs4XubFDHDhnum2dsEajiPH7uHTr4Rr4GYoPjbzbGMnKZ/7G6X7cZLfkt01Ma+BHCVwP3JioVZ2CMH9Zmavr8PO1DZpGxV0EcUHYhA/hLb+ckjURMG0DQvmIWNPQKCMSzW2vL9Y+lD+6opmZZzEZuAf6jSU7ST40h3i/UXOxKF+ODcrqmYDpUk0/W29zlf+YYanrWObMn4aVKw2b/nqFgoTDfd5a8KpEZALOOru/uVB/9hSHaQVAzFilsxHALDIwD6Q35x/Kb6sLvB/vU/udjds8FLXXTWAgeaDEsR69SW8NFVXRNVCAoc45JRSQzWeBORS9YnCxXioWb4LI+t5+hMi119y0uhcONvdTMYdFs1TTOJYRjTs99WGZb8i4UYUtyYMAphyf0+FFfLkQKzsKEMRtJvI8+KdYOP+vCfesFtbw2lTdXeUWAQuX8=
    file_glob: true
    file: dist/*
    on:
      repo: arnested/go-healthy
      tags: true
  # Refresh godoc.org documentation
  - provider: script
    script: 'curl --silent -X POST -H "Content-Type: application/x-www-form-urlencoded" https://godoc.org/-/refresh --data "path=arnested.dk%2Fgo%2Fhealthy"'
    on:
      repo: arnested/go-healthy
      branch: master
  # Refresh goreportcard.com report
  - provider: script
    script: 'curl --silent -X POST -H "Content-Type: application/x-www-form-urlencoded" https://goreportcard.com/checks --data "repo=arnested.dk%2Fgo%2Fhealthy"'
    on:
      repo: arnested/go-healthy
      branch: master
