---
whitelist:
  - Apache-2.0
  - FreeBSD
  - MIT
  - BSD-2-Clause
  - BSD-3-Clause

exceptions:
  - github.com/opencontainers/go-digest # Uses Apache License Version 2.0
  - github.com/gogo/protobuf/proto # Uses a BSD-3-Clause
